services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    command: mongod --bind_ip_all
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: