#    This is a template for the credentials.yaml file.
#    Fill in your credentials and rename this file to credentials.yaml.
#    Keep this file private by adding it to your .gitignore.

# Reddit API credentials
reddit:
  client_id: "your-client-id"
  client_secret: "your-client-secret"
  user_agent: "your-user-agent"
  username: "username"  # Optional
  password: "password"  # Optional

# Twitter API credentials
twitter:
  bearer_token: your-bearer-token
  api_key: your-api-key
  api_secret: your-api-secret
  access_token: your-access-token
  access_token_secret: your-access-token-secret

# News API credentials (not used)
# news:
#   api_key: YOUR_API_KEY

mongodb:
  connection_string: "your-mongodb-connection-string"
  database: "your-database-name"
  volumes:
    - "path-to-mongodb-data" # not used in project