# MongoDB settings - present in credentials.yaml
mongodb:
  connection_string: "port-to-mongodb"
  database: "db-name"
  volumes:
    - "path-to-mongodb-data" # Optional

# Reddit extraction settings
reddit:
  subreddits:
    - "worldnews"
    - "news"
    - "politics"
    - "technology"
    - "science"
  posts_per_subreddit: 20
  sort: "hot"

  # Twitter extraction settings
twitter:
  search_terms:
    - "politics"
    - "climate change"
    - "economy"
    - "world news"
    - "technology"
  tweets_per_term: 0 # 0 for testing. Set to 20 later
  include_retweets: false

news:
  sources:
    - "bbc.com"
    - "cnn.com"
    - "reuters.com"
  categories:
    bbc: ["news", "business", "innovation"]
    cnn: ["world", "business", "politics"]
  articles_per_source: 20