# MongoDB settings
mongodb:
  connection_string: "mongodb://host.docker.internal:27017/"
  database: "global_sentiment"

# Reddit extraction settings
reddit:
  subreddits:
    - "worldnews"
    - "news"
    - "politics"
    - "technology"
    - "science"
  posts_per_subreddit: 5
  sort: "hot"

  # Twitter extraction settings
twitter:
  search_terms:
    - "politics"
    - "climate change"
    - "economy"
    - "trump"
    - "technology"
  tweets_per_term: 10 # 0 for testing. Set to 100 later
  include_retweets: false

news:
  sources:
    - "bbc.com"
    - "cnn.com"
    - "reuters.com"
  categories:
    bbc: ["news", "business", "innovation"]
    cnn: ["world", "business", "politics"]
  articles_per_source: 2